config/routes.rb
Rails.application.routes.draw do
  get 'comments/index'
  get 'posts/index'
  devise_for :users
  get 'homes/index'

  resources :posts do
resources :comments
end
  root 'homes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length:{minimum: 3}
  validates :body, presence: true, length:{minimum: 10}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    @comment.user_id = current_user.id
    @comment.save
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

    private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def show
  @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)
  @post.user_id = current_user.id
    if @post.save
    redirect_to @post
  else
    redirect_to 'new'
  end
  end

  def edit
    @post = Post.find(params[:id])
  end
  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

    def destroy
      @post = Post.find(params[:id])
      @post.destroy
      redirect_to posts_path
  end
  private
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<!-- partial for comments that are generated-->

<div class="divider"></div>
<h5>Comments</h5>
<% @post.comments.each do |comment|%>
<div>
<p><strong><%= comment.commenter %></strong> says...</p>
<%= comment.body %>
</div>
<!-- Delete comment buttons -->
<p><%= link_to 'Delete Comment', post_comment_path(@post, comment), method: :Delete, data: {confirm: 'Are you Sure?'} %></p>
<%end%>

app/views/comments/_formComment.html.erb
<!-- partial for form that creates the comments -->

<div class="divider"></div>
<h6>Add Comment</h6>
<%= form_for([@post, @post.comments.build]) do |f|%>

</p>
<%= f.label :commenter%> <br>
<%= f.text_field :commenter%>
<p>

<p>
<%= f.label :body%><br>
<%= f.text_area :body%>
</p>

<!-- submit button has a style added to it -->
  <a class="waves-effect waves-light btn"><%= f.submit%></a>

<% end %>

app/views/homes/index.html.erb
<!-- Home index that contains the about statement -->

<div class="container">
<h1>About Mumbler</h1>
<h5>
We are a blog site that allows users to create posts and comment on them.
We are currently using materialize to style the site and it was created with Ruby on Rails.
Please enjoy what we have and hopefully later it will be improved.
</h5>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mumbler</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Link for buttons and icon styling from materialize -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- turbolinks -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- devise alerts and errors for mistakes or successful sign in -->
    <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <!-- Navigation -->
      <nav>
        <div class="nav-wrapper">
          <a href="#" class="brand-logo center">Mumbler</a>
          <ul class="left hide-on-med-and-down">
    <!-- If statement for navigation -->
    <!-- Only allow users full access after sign in or up -->
      <% if user_signed_in? %>
      <li><%= link_to 'All Blogs', posts_path %></li>
      <li><%= link_to 'New post', new_post_path%></li>
      <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
      <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
      <% else %>
      <li><%= link_to 'Sign In', new_user_session_path %></li>
      <% end %>
      </ul>
    </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<!-- Form for editing a blog post -->
<h3>Edit a Post</h3>
<%= form_for @post do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title%>

  <%= f.label :body %><br>
  <%= f.text_area :body %>

<!-- Button styling from materialize -->
<a class="waves-effect waves-light btn"><%= f.submit %></a>

<% end %>

app/views/posts/index.html.erb
<!-- Headers in row class within own columns above blog posts index -->
  <div class="row">
    <!-- Title of posts -->
    <div class="col s3">
      <h4 class="left-align">Title</h4>
    </div>
    <!-- Post content -->
    <div class="col s3">
      <h4 class="center-align">Post</h4>
    </div>
    <!-- Time posts creation -->
    <div class="col s3">
      <h4 class="right-align">Created at</h4>
    </div>
  </div>

    <!-- Post generated with do each -->
    <% @posts.each do |post|%>
    <div class="row">
      <!-- Titles for post -->
      <div class="col s3">
      <%= post.title %>
    </div>
    <div class="col s3">
      <!-- Trucated post so user can preview post -->
      <p class="center-align" ><%= truncate(post.body, length: 20) %></p>
    </div>

        <div class="col s3" >
          <!-- Time post was created-->
      <p class="right-align"><%= time_ago_in_words(post.created_at) %> ago</p>
    </div>
    <div class="col s3">
      <!-- Posts options -->
      <!-- Link to full posts -->
      <p><%= link_to 'Full post', post_path(post)%></p>
      <% if current_user.id == post.user_id %>
      <!-- Edit Posts path -->
      <p><%= link_to 'Edit', edit_post_path(post)%></p>
      <!-- Posts deletion -->
      <p><%= link_to 'Delete', post_path(post), method: :Delete, data: {confirm: "are you sure??"}%>
        <% end %>
    </div>

    </div>
    <!-- border to seperate each posts generated -->
     <div class="divider"></div>
    <%end%>

  </div>

app/views/posts/new.html.erb
<!-- Form to create new posts -->
<h1>Create a new Post</h1>
<!-- After posts generated send to posts index -->
<%= form_for :post, url: posts_path do |f| %>


<% if @post.errors.any? %>
<!-- If theres any issues in it won't save and gives message -->
<div id="Error_explantion">
  <h2>
    <%= pluralize(@post.errors.count, "error")%>
    Won't save article:
  </h2>
    <ul>
    <%@post.errors.full_messages.each do |msg|%>

  <li>
    <%= msg %>
  </li>
  </ul>
  <% end %>
  <% end %>
<!-- Otherwise create posts -->
  <%= f.label :title %><br>
  <%= f.text_field :title %>

  <%= f.label :body %><br>
  <%= f.text_area :body %>

    <a class="waves-effect waves-light btn"><%= f.submit %></a>

<% end %>

app/views/posts/show.html.erb
<!-- Show page that generates full posts -->
<div class="row">
<div class="col s12">
  <!-- Entire post in column that takes up screen -->
<h4><%= @post.title %></h4>
<p> Created <%= time_ago_in_words(@post.created_at) %> ago</p>
<h5><%= @post.body %></h5>
</div>
<div class="col s6">
  <!-- comment form and comments share the screen. Render at bottom -->
<%= render 'comments/comment'%>
</div>
<div class="col s6">
<%= render 'comments/formComment'%>
</div>
</div>